language: scala

jdk:
  - openjdk8

before_install:
  - git clone https://github.com/wlingxiao/fetches.git
  - cd fetches
  - sbt publishLocal
  - cd ..

script:
  - sbt clean coverage test it:test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)